import { Geist, Geist_Mono } from "next/font/google";
// import "./sglobals.css";
import "@/app/globals.css";

import Sidebar from "../components/features/navigation/Sidebar";
import { AccentProvider } from "../context/accentContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Happy Star Rail",
  // description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* <main className="flex h-screen overflow-hidden">
          <Sidebar />
          {children}
        </main> */}

        <AccentProvider>
          <div style={{ display: "flex" }}>
            <Sidebar />
            <main style={{ flex: 1 }}>{children}</main>
          </div>
        </AccentProvider>
      </body>
    </html>
  );
}
