import { Geist, Geist_Mono } from "next/font/google";
// import "./sglobals.css";
import "@/app/globals.css";

import Sidebar from "../components/features/navigation/Sidebar";
import { AccentProvider } from "../context/accentContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Happy Star Rail",
  // description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="h-full">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased h-full`}
      >
        <AccentProvider>
          <div className="flex h-full min-h-screen">
            <Sidebar />
            <main className="flex-1 overflow-auto">{children}</main>
          </div>
        </AccentProvider>
      </body>
    </html>
  );
}
