import Sidebar from "../components/mainPages/Sidebar";

import { Geist, Geist_Mono } from "next/font/google";
// import "./sglobals.css";
import "@/app/globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Happy Star Rail",
  // description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <main className="flex h-screen overflow-hidden">
          {/* Sidebar kiri */}
          <Sidebar />
          {children}
        </main>
      </body>
    </html>
  );
}
