const bots = [
  {
    id: "herta",
    name: "Herta",
    title: "Genius Society #83",
    affil: "Herta Station Space",
    image: "/img/herta-profile.jpg",
    color: "purple",
  },
  {
    id: "himeko",
    name: "Himeko",
    title: "Trailblazer",
    affil: "Astral Express",
    image: "/img/himeko-profile.jpg",
    color: "red",
  },
  {
    id: "march-7th",
    name: "March 7th",
    title: "Trailblazer",
    affil: "Astral Express",
    image: "/img/march-7th.jpg",
    color: "red",
  },
  {
    id: "welt",
    name: "Welt",
    title: "Trailblazer",
    affil: "Astral Express",
    image: "/img/welt.jpg",
    color: "gold",
  },
  {
    id: "dan-heng",
    name: "Dan Heng",
    title: "Trailblazer",
    affil: "Astral Express",
    image: "/img/dan-heng.jpg",
    color: "green",
  },
  {
    id: "pom-pom",
    name: "Pom Pom",
    title: "Trailblazer",
    affil: "Astral Express",
    image: "/img/pompom-icon.ico",
    color: "red",
  },
  {
    id: "kafka",
    name: "Kafka",
    title: "Stellaron Hunter",
    affil: "Stellaron Hunter",
    image: "/img/kafka-profile.jpg",
    color: "purple",
  },
];
